### ISSUE TITLE
Support multiple proto path contexts, similar to kubectl context.

### ISSUE THREAD

**Issue by marshallbrekka** [wearefair/gurl#6]
While our use-case largely revolves around a mego-repo of protos, it would be nice to support setting up multiple proto contexts (separate import and service paths) that could easily be switched between.

Maybe something like
```yaml
contexts:
  name: project-a
  importPaths:
    - /my/dependencies
  servicePaths:
    - /my/services

currentContext: project-a
```

which could be switched between like so
```bash
$ gurl set-context project-a
```
